// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Query
	Result
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Domain Query struct. Used by domain-query and datapipeline-query
type Query struct {
	// A unique ID of this query (Will be included in the results)
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	// The remaining fields depend on the type of the query
	//
	// Types that are valid to be assigned to QueryType:
	//	*Query_AdHocQuery_
	//	*Query_TypedQuery_
	//	*Query_MetricQuery_
	QueryType isQuery_QueryType `protobuf_oneof:"query_type"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isQuery_QueryType interface {
	isQuery_QueryType()
}

type Query_AdHocQuery_ struct {
	AdHocQuery *Query_AdHocQuery `protobuf:"bytes,3,opt,name=ad_hoc_query,json=adHocQuery,oneof"`
}
type Query_TypedQuery_ struct {
	TypedQuery *Query_TypedQuery `protobuf:"bytes,4,opt,name=typed_query,json=typedQuery,oneof"`
}
type Query_MetricQuery_ struct {
	MetricQuery *Query_MetricQuery `protobuf:"bytes,5,opt,name=metric_query,json=metricQuery,oneof"`
}

func (*Query_AdHocQuery_) isQuery_QueryType()  {}
func (*Query_TypedQuery_) isQuery_QueryType()  {}
func (*Query_MetricQuery_) isQuery_QueryType() {}

func (m *Query) GetQueryType() isQuery_QueryType {
	if m != nil {
		return m.QueryType
	}
	return nil
}

func (m *Query) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Query) GetAdHocQuery() *Query_AdHocQuery {
	if x, ok := m.GetQueryType().(*Query_AdHocQuery_); ok {
		return x.AdHocQuery
	}
	return nil
}

func (m *Query) GetTypedQuery() *Query_TypedQuery {
	if x, ok := m.GetQueryType().(*Query_TypedQuery_); ok {
		return x.TypedQuery
	}
	return nil
}

func (m *Query) GetMetricQuery() *Query_MetricQuery {
	if x, ok := m.GetQueryType().(*Query_MetricQuery_); ok {
		return x.MetricQuery
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Query) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Query_OneofMarshaler, _Query_OneofUnmarshaler, _Query_OneofSizer, []interface{}{
		(*Query_AdHocQuery_)(nil),
		(*Query_TypedQuery_)(nil),
		(*Query_MetricQuery_)(nil),
	}
}

func _Query_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Query)
	// query_type
	switch x := m.QueryType.(type) {
	case *Query_AdHocQuery_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AdHocQuery); err != nil {
			return err
		}
	case *Query_TypedQuery_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TypedQuery); err != nil {
			return err
		}
	case *Query_MetricQuery_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MetricQuery); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Query.QueryType has unexpected type %T", x)
	}
	return nil
}

func _Query_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Query)
	switch tag {
	case 3: // query_type.ad_hoc_query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Query_AdHocQuery)
		err := b.DecodeMessage(msg)
		m.QueryType = &Query_AdHocQuery_{msg}
		return true, err
	case 4: // query_type.typed_query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Query_TypedQuery)
		err := b.DecodeMessage(msg)
		m.QueryType = &Query_TypedQuery_{msg}
		return true, err
	case 5: // query_type.metric_query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Query_MetricQuery)
		err := b.DecodeMessage(msg)
		m.QueryType = &Query_MetricQuery_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Query_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Query)
	// query_type
	switch x := m.QueryType.(type) {
	case *Query_AdHocQuery_:
		s := proto.Size(x.AdHocQuery)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_TypedQuery_:
		s := proto.Size(x.TypedQuery)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_MetricQuery_:
		s := proto.Size(x.MetricQuery)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Fields needed for an ADHOC query
type Query_AdHocQuery struct {
	// The query string
	QueryString string `protobuf:"bytes,1,opt,name=query_string,json=queryString" json:"query_string,omitempty"`
	// Additional params needed to perform the query
	QueryParams map[string]string `protobuf:"bytes,2,rep,name=query_params,json=queryParams" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Additional metadata associated with the query
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Query_AdHocQuery) Reset()                    { *m = Query_AdHocQuery{} }
func (m *Query_AdHocQuery) String() string            { return proto.CompactTextString(m) }
func (*Query_AdHocQuery) ProtoMessage()               {}
func (*Query_AdHocQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Query_AdHocQuery) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *Query_AdHocQuery) GetQueryParams() map[string]string {
	if m != nil {
		return m.QueryParams
	}
	return nil
}

func (m *Query_AdHocQuery) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Fields needed for a TYPED query
type Query_TypedQuery struct {
	// The name of the type
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *Query_TypedQuery) Reset()                    { *m = Query_TypedQuery{} }
func (m *Query_TypedQuery) String() string            { return proto.CompactTextString(m) }
func (*Query_TypedQuery) ProtoMessage()               {}
func (*Query_TypedQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Query_TypedQuery) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Fields needed for a METRIC query
type Query_MetricQuery struct {
	// The ID of the metric in the catalog
	MetricId string `protobuf:"bytes,1,opt,name=metric_id,json=metricId" json:"metric_id,omitempty"`
	// The earliest (inclusive) timestamp desired
	Start int64 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	// The latest (inclusive) timestamp desired (set to 0 to get latest)
	End int64 `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	// Return only the most recent X datapoints within the time range.
	Latest int32 `protobuf:"varint,4,opt,name=latest" json:"latest,omitempty"`
}

func (m *Query_MetricQuery) Reset()                    { *m = Query_MetricQuery{} }
func (m *Query_MetricQuery) String() string            { return proto.CompactTextString(m) }
func (*Query_MetricQuery) ProtoMessage()               {}
func (*Query_MetricQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Query_MetricQuery) GetMetricId() string {
	if m != nil {
		return m.MetricId
	}
	return ""
}

func (m *Query_MetricQuery) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Query_MetricQuery) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Query_MetricQuery) GetLatest() int32 {
	if m != nil {
		return m.Latest
	}
	return 0
}

// Query result struct
type Result struct {
	// Identifies the ResultInstance that owns this data
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Identifies the QueryInstance from which this ResultInstance was generated
	QueryId string `protobuf:"bytes,2,opt,name=queryId" json:"queryId,omitempty"`
	// Metadata associated with this result
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timestamp when this result was retrieved
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	// Result record
	//
	// Types that are valid to be assigned to Result:
	//	*Result_MetricResult_
	Result isResult_Result `protobuf_oneof:"result"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isResult_Result interface {
	isResult_Result()
}

type Result_MetricResult_ struct {
	MetricResult *Result_MetricResult `protobuf:"bytes,5,opt,name=metric_result,json=metricResult,oneof"`
}

func (*Result_MetricResult_) isResult_Result() {}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Result) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *Result) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Result) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Result) GetMetricResult() *Result_MetricResult {
	if x, ok := m.GetResult().(*Result_MetricResult_); ok {
		return x.MetricResult
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Result) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Result_OneofMarshaler, _Result_OneofUnmarshaler, _Result_OneofSizer, []interface{}{
		(*Result_MetricResult_)(nil),
	}
}

func _Result_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Result)
	// result
	switch x := m.Result.(type) {
	case *Result_MetricResult_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MetricResult); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Result.Result has unexpected type %T", x)
	}
	return nil
}

func _Result_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Result)
	switch tag {
	case 5: // result.metric_result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result_MetricResult)
		err := b.DecodeMessage(msg)
		m.Result = &Result_MetricResult_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Result_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Result)
	// result
	switch x := m.Result.(type) {
	case *Result_MetricResult_:
		s := proto.Size(x.MetricResult)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Result_MetricResult struct {
	// Name of this metric
	MetricName string `protobuf:"bytes,1,opt,name=metric_name,json=metricName" json:"metric_name,omitempty"`
	// Metric ID
	MetricId string `protobuf:"bytes,2,opt,name=metric_id,json=metricId" json:"metric_id,omitempty"`
	// Value of this metric
	Value float64 `protobuf:"fixed64,3,opt,name=value" json:"value,omitempty"`
	// Timestamp associated with this metric value
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Result_MetricResult) Reset()                    { *m = Result_MetricResult{} }
func (m *Result_MetricResult) String() string            { return proto.CompactTextString(m) }
func (*Result_MetricResult) ProtoMessage()               {}
func (*Result_MetricResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *Result_MetricResult) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *Result_MetricResult) GetMetricId() string {
	if m != nil {
		return m.MetricId
	}
	return ""
}

func (m *Result_MetricResult) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Result_MetricResult) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Query)(nil), "test.Query")
	proto.RegisterType((*Query_AdHocQuery)(nil), "test.Query.AdHocQuery")
	proto.RegisterType((*Query_TypedQuery)(nil), "test.Query.TypedQuery")
	proto.RegisterType((*Query_MetricQuery)(nil), "test.Query.MetricQuery")
	proto.RegisterType((*Result)(nil), "test.Result")
	proto.RegisterType((*Result_MetricResult)(nil), "test.Result.MetricResult")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0x38, 0x24, 0x63, 0x17, 0x55, 0x23, 0x54, 0x8c, 0x8b, 0xd4, 0x50, 0x21, 0x91,
	0x93, 0x0f, 0x45, 0x42, 0x50, 0x10, 0x2a, 0x91, 0x90, 0x52, 0xa4, 0x22, 0x30, 0xdc, 0xa3, 0x25,
	0xbb, 0x0a, 0x86, 0xd8, 0x0e, 0xbb, 0x1b, 0xa4, 0xf4, 0xc4, 0x47, 0xf0, 0x0b, 0xfc, 0x04, 0x5f,
	0x87, 0x76, 0x76, 0xed, 0xa4, 0x0d, 0x45, 0x42, 0xbd, 0xcd, 0x9b, 0x9d, 0xf7, 0x66, 0x67, 0xdf,
	0xd8, 0x00, 0x5a, 0x28, 0x9d, 0x2d, 0x64, 0xad, 0x6b, 0xec, 0x98, 0xf8, 0xe8, 0x57, 0x08, 0xe1,
	0xfb, 0xa5, 0x90, 0x2b, 0xbc, 0x0d, 0x7e, 0xc1, 0x13, 0x7f, 0xe0, 0x0d, 0xfb, 0xb9, 0x5f, 0x70,
	0x3c, 0x81, 0x98, 0xf1, 0xc9, 0xe7, 0x7a, 0x3a, 0xf9, 0x66, 0xce, 0x93, 0x60, 0xe0, 0x0d, 0xa3,
	0xe3, 0xfd, 0x8c, 0x24, 0x88, 0x92, 0xbd, 0xe2, 0xe3, 0x7a, 0x4a, 0xe1, 0x78, 0x27, 0x07, 0xd6,
	0x22, 0x7c, 0x06, 0x91, 0x5e, 0x2d, 0x04, 0x77, 0xd4, 0xce, 0x36, 0xf5, 0xa3, 0x39, 0x6e, 0xa9,
	0xba, 0x45, 0xf8, 0x02, 0xe2, 0x52, 0x68, 0x59, 0x34, 0x6d, 0x43, 0xe2, 0xde, 0xdd, 0xe4, 0x9e,
	0xd3, 0x79, 0x43, 0x8e, 0xca, 0x35, 0x4c, 0x7f, 0xfb, 0x00, 0xeb, 0x5b, 0xe1, 0x03, 0x88, 0x49,
	0x65, 0xa2, 0xb4, 0x2c, 0xaa, 0x59, 0xe2, 0xd1, 0x74, 0x11, 0xe5, 0x3e, 0x50, 0x0a, 0xdf, 0x34,
	0x25, 0x0b, 0x26, 0x59, 0xa9, 0x12, 0x7f, 0x10, 0x0c, 0xa3, 0xe3, 0x47, 0x7f, 0x1f, 0xd3, 0x26,
	0xde, 0x51, 0xe5, 0xeb, 0x4a, 0xcb, 0x95, 0xd3, 0xb2, 0x19, 0x3c, 0x85, 0x5e, 0x29, 0x34, 0xe3,
	0x4c, 0xb3, 0x24, 0x20, 0x9d, 0x87, 0xd7, 0xe8, 0x9c, 0xbb, 0x32, 0x2b, 0xd2, 0xb2, 0xd2, 0x97,
	0xb0, 0x77, 0xb5, 0x05, 0xee, 0x41, 0xf0, 0x55, 0xac, 0xdc, 0xdd, 0x4d, 0x88, 0x77, 0x20, 0xfc,
	0xce, 0xe6, 0x4b, 0xe1, 0xdc, 0xb2, 0xe0, 0xc4, 0x7f, 0xea, 0xa5, 0xcf, 0x61, 0xf7, 0x92, 0xf4,
	0x7f, 0x91, 0x07, 0x00, 0x6b, 0x5b, 0x10, 0xa1, 0x63, 0x6c, 0x71, 0x54, 0x8a, 0xd3, 0x2f, 0x10,
	0x6d, 0x3c, 0x3e, 0x1e, 0x40, 0xdf, 0x79, 0x55, 0x70, 0x57, 0xd7, 0xb3, 0x89, 0x33, 0x6e, 0xfa,
	0x28, 0xcd, 0xa4, 0xa6, 0x3e, 0x41, 0x6e, 0x81, 0xb9, 0x8f, 0xa8, 0x38, 0x2d, 0x53, 0x90, 0x9b,
	0x10, 0xf7, 0xa1, 0x3b, 0x67, 0xe6, 0x95, 0x68, 0x4d, 0xc2, 0xdc, 0xa1, 0x51, 0x0c, 0x60, 0x8d,
	0x31, 0x9d, 0x8f, 0x7e, 0x06, 0xd0, 0xcd, 0x85, 0x5a, 0xce, 0xb5, 0x5b, 0x54, 0xaf, 0x5d, 0xd4,
	0x04, 0x6e, 0x51, 0xe1, 0x59, 0xb3, 0xbd, 0x0d, 0xc4, 0x27, 0x5b, 0x7e, 0xa4, 0xd6, 0x0f, 0xab,
	0x74, 0x9d, 0x0b, 0x78, 0x1f, 0xfa, 0xba, 0x28, 0x85, 0xd2, 0xac, 0x5c, 0xd0, 0xad, 0x82, 0x7c,
	0x9d, 0xc0, 0x53, 0xd8, 0x75, 0x53, 0x4b, 0x92, 0x71, 0x2b, 0x7a, 0xef, 0xaa, 0xb4, 0x2c, 0xa6,
	0x16, 0x8c, 0x77, 0x72, 0xb7, 0xd3, 0x16, 0xdf, 0xcc, 0xa5, 0x1f, 0x1e, 0xc4, 0x9b, 0xea, 0x78,
	0x08, 0xee, 0x13, 0x98, 0x54, 0xac, 0x6c, 0xfc, 0x02, 0x9b, 0x7a, 0xcb, 0x4a, 0x71, 0xd9, 0x26,
	0x7f, 0xdb, 0x26, 0xdb, 0xc8, 0x58, 0xe2, 0xb9, 0x46, 0xff, 0x7e, 0x81, 0x51, 0x0f, 0xba, 0x76,
	0xf4, 0xd1, 0x21, 0x1c, 0xd4, 0x72, 0x96, 0x5d, 0x88, 0xaa, 0x56, 0x2a, 0xbb, 0x28, 0xaa, 0x99,
	0xfd, 0xbb, 0x64, 0xf6, 0xb3, 0xf0, 0x3e, 0x75, 0x09, 0x3e, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0x62, 0xac, 0xb6, 0x7a, 0x04, 0x00, 0x00,
}
